# Generated by Django 5.0.3 on 2024-03-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="conversation_participant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="chat.conversationparticipant",
            ),
            preserve_default=False,
        ),
    ]
