# Generated by Django 5.0.3 on 2024-03-22 13:59

import loomi_hub.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=loomi_hub.post.models.upload_to
            ),
        ),
    ]
