# Generated by Django 5.0.3 on 2024-03-24 21:33

import loomi_hub.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=loomi_hub.post.models.upload_to
            ),
        ),
    ]
